#!/usr/bin/env bash
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 3
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 10
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 20
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 3 -prior_pi 0.75
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 3 -prior_pi 0.5
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 3 -prior_pi 0.25
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 3 -prior_pi 1.0 -prior_sigma_1 0.37
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 3 -prior_pi 0.75 -prior_sigma_1 0.37
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 3 -prior_pi 0.5 -prior_sigma_1 0.37
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 3 -prior_pi 0.25 -prior_sigma_1 0.37
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 3 -prior_pi 1.0 -prior_sigma_1 0.135
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 3 -prior_pi 0.75 -prior_sigma_1 0.135
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 3 -prior_pi 0.5 -prior_sigma_1 0.135
python src/scripts/run.py -dataset "synthetic" -dataset_model 1 -data_path "data/synthetic_model_1" -algo "bayesian_lstm" -rnn_units 32 -bs 32 -ep 50 -output_path "output/exp_synthetic_model_1" -mc_samples 1000 -particles 3 -prior_pi 0.25 -prior_sigma_1 0.135

